{% set name = "alibabacloud-openapi-util" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_openapi_util-{{ version }}.tar.gz
  sha256: ebbc3906f554cb4bf8f513e43e8a33e8b6a3d4a0ef13617a0e14c3dda8ef52a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - alibabacloud-tea-util >=0.0.2
    - cryptography >=3.0.0

test:
  imports:
    - alibabacloud_openapi_util
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aliyun/darabonba-openapi-util
  summary: Aliyun Tea OpenApi Library for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
