{% set name = "alibabacloud-openapi-util" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_openapi_util-{{ version }}.tar.gz
  sha256: 87022b9dcb7593a601f7a40ca698227ac3ccb776b58cb7b06b8dc7f510995c34

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - alibabacloud-tea-util <1.0.0,>=0.3.13
    - cryptography >=3.0.0

test:
  imports:
    - alibabacloud_openapi_util
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aliyun/darabonba-openapi-util
  summary: Aliyun Tea OpenApi Library for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
